### ISSUE TITLE
Error when adding in Fragment

### ISSUE THREAD

**Issue by jpabanil** [KingsMentor/MobileVisionBarcodeScanner#33]
Hi,

I was trying to use your library in our project but got this error when I open the MainActivity that holds the fragment. I hope you can help me as soon as possible.

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.samples.vision.barcodereader.BarcodeCapture.setRetrieval(xyz.belvi.mobilevisionbarcodescanner.BarcodeRetriever)' on a null object reference at ca.easyreg.easyexhibitor.fragments.BarcodeScanner.onCreateView(BarcodeScanner.java:108)

Thanks in Advance!

J

**Comment by jpabanil** [comment]
This is now fixed...

**Comment by kasp4770** [comment]
jpabanil how did you fix it? Do you remember?

**Comment by mostafaaddam** [comment]
This is still not working on fragment i tried to put barcodeCapture.setRetrieval(this); its crashing with  Attempt to invoke virtual method 'void com.google.android.gms.samples.vision.barcodereader.BarcodeCapture.setRetrieval(xyz.belvi.mobilevisionbarcodescanner.BarcodeRetriever)' on a null object reference

**Comment by KushalMehta1995** [comment]
Anyone got any solution regarding this? i'm too facing this problem.
